// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package guku

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type PlatformBindingStatus string

const (
	PlatformBindingStatusPending   PlatformBindingStatus = "Pending"
	PlatformBindingStatusSucceeded PlatformBindingStatus = "Succeeded"
	PlatformBindingStatusFailed    PlatformBindingStatus = "Failed"
	PlatformBindingStatusError     PlatformBindingStatus = "Error"
)

// __createClusterInput is used internally by genqlient
type __createClusterInput struct {
	Name       string `json:"name"`
	Server     string `json:"server"`
	Ca         string `json:"ca"`
	Token      string `json:"token"`
	ApiVersion string `json:"apiVersion"`
	Context    string `json:"context"`
}

// GetName returns __createClusterInput.Name, and is useful for accessing the field via an interface.
func (v *__createClusterInput) GetName() string { return v.Name }

// GetServer returns __createClusterInput.Server, and is useful for accessing the field via an interface.
func (v *__createClusterInput) GetServer() string { return v.Server }

// GetCa returns __createClusterInput.Ca, and is useful for accessing the field via an interface.
func (v *__createClusterInput) GetCa() string { return v.Ca }

// GetToken returns __createClusterInput.Token, and is useful for accessing the field via an interface.
func (v *__createClusterInput) GetToken() string { return v.Token }

// GetApiVersion returns __createClusterInput.ApiVersion, and is useful for accessing the field via an interface.
func (v *__createClusterInput) GetApiVersion() string { return v.ApiVersion }

// GetContext returns __createClusterInput.Context, and is useful for accessing the field via an interface.
func (v *__createClusterInput) GetContext() string { return v.Context }

// __createPlatformBindingInput is used internally by genqlient
type __createPlatformBindingInput struct {
	PlatformVersion  string `json:"platformVersion"`
	PlatformID       string `json:"platformID"`
	PlatformConfigID string `json:"platformConfigID"`
	ClusterID        string `json:"clusterID"`
}

// GetPlatformVersion returns __createPlatformBindingInput.PlatformVersion, and is useful for accessing the field via an interface.
func (v *__createPlatformBindingInput) GetPlatformVersion() string { return v.PlatformVersion }

// GetPlatformID returns __createPlatformBindingInput.PlatformID, and is useful for accessing the field via an interface.
func (v *__createPlatformBindingInput) GetPlatformID() string { return v.PlatformID }

// GetPlatformConfigID returns __createPlatformBindingInput.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *__createPlatformBindingInput) GetPlatformConfigID() string { return v.PlatformConfigID }

// GetClusterID returns __createPlatformBindingInput.ClusterID, and is useful for accessing the field via an interface.
func (v *__createPlatformBindingInput) GetClusterID() string { return v.ClusterID }

// __createPlatformConfigInput is used internally by genqlient
type __createPlatformConfigInput struct {
	Config          string `json:"config"`
	Name            string `json:"name"`
	PlatformID      string `json:"platformID"`
	PlatformVersion string `json:"platformVersion"`
}

// GetConfig returns __createPlatformConfigInput.Config, and is useful for accessing the field via an interface.
func (v *__createPlatformConfigInput) GetConfig() string { return v.Config }

// GetName returns __createPlatformConfigInput.Name, and is useful for accessing the field via an interface.
func (v *__createPlatformConfigInput) GetName() string { return v.Name }

// GetPlatformID returns __createPlatformConfigInput.PlatformID, and is useful for accessing the field via an interface.
func (v *__createPlatformConfigInput) GetPlatformID() string { return v.PlatformID }

// GetPlatformVersion returns __createPlatformConfigInput.PlatformVersion, and is useful for accessing the field via an interface.
func (v *__createPlatformConfigInput) GetPlatformVersion() string { return v.PlatformVersion }

// __createPrivateClusterInput is used internally by genqlient
type __createPrivateClusterInput struct {
	Name               string `json:"name"`
	Token              string `json:"token"`
	PrivateTunnelToken string `json:"privateTunnelToken"`
	ApiVersion         string `json:"apiVersion"`
	Context            string `json:"context"`
}

// GetName returns __createPrivateClusterInput.Name, and is useful for accessing the field via an interface.
func (v *__createPrivateClusterInput) GetName() string { return v.Name }

// GetToken returns __createPrivateClusterInput.Token, and is useful for accessing the field via an interface.
func (v *__createPrivateClusterInput) GetToken() string { return v.Token }

// GetPrivateTunnelToken returns __createPrivateClusterInput.PrivateTunnelToken, and is useful for accessing the field via an interface.
func (v *__createPrivateClusterInput) GetPrivateTunnelToken() string { return v.PrivateTunnelToken }

// GetApiVersion returns __createPrivateClusterInput.ApiVersion, and is useful for accessing the field via an interface.
func (v *__createPrivateClusterInput) GetApiVersion() string { return v.ApiVersion }

// GetContext returns __createPrivateClusterInput.Context, and is useful for accessing the field via an interface.
func (v *__createPrivateClusterInput) GetContext() string { return v.Context }

// __deleteClusterInput is used internally by genqlient
type __deleteClusterInput struct {
	Id string `json:"id"`
}

// GetId returns __deleteClusterInput.Id, and is useful for accessing the field via an interface.
func (v *__deleteClusterInput) GetId() string { return v.Id }

// __deletePlatformBindingInput is used internally by genqlient
type __deletePlatformBindingInput struct {
	ClusterID         string `json:"clusterID"`
	PlatformBindingID string `json:"platformBindingID"`
}

// GetClusterID returns __deletePlatformBindingInput.ClusterID, and is useful for accessing the field via an interface.
func (v *__deletePlatformBindingInput) GetClusterID() string { return v.ClusterID }

// GetPlatformBindingID returns __deletePlatformBindingInput.PlatformBindingID, and is useful for accessing the field via an interface.
func (v *__deletePlatformBindingInput) GetPlatformBindingID() string { return v.PlatformBindingID }

// __deletePlatformConfigInput is used internally by genqlient
type __deletePlatformConfigInput struct {
	PlatformID       string `json:"platformID"`
	PlatformConfigID string `json:"platformConfigID"`
}

// GetPlatformID returns __deletePlatformConfigInput.PlatformID, and is useful for accessing the field via an interface.
func (v *__deletePlatformConfigInput) GetPlatformID() string { return v.PlatformID }

// GetPlatformConfigID returns __deletePlatformConfigInput.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *__deletePlatformConfigInput) GetPlatformConfigID() string { return v.PlatformConfigID }

// __getClusterInput is used internally by genqlient
type __getClusterInput struct {
	Id string `json:"id"`
}

// GetId returns __getClusterInput.Id, and is useful for accessing the field via an interface.
func (v *__getClusterInput) GetId() string { return v.Id }

// __getPlatformBindingInput is used internally by genqlient
type __getPlatformBindingInput struct {
	ClusterID         string `json:"clusterID"`
	PlatformBindingID string `json:"platformBindingID"`
}

// GetClusterID returns __getPlatformBindingInput.ClusterID, and is useful for accessing the field via an interface.
func (v *__getPlatformBindingInput) GetClusterID() string { return v.ClusterID }

// GetPlatformBindingID returns __getPlatformBindingInput.PlatformBindingID, and is useful for accessing the field via an interface.
func (v *__getPlatformBindingInput) GetPlatformBindingID() string { return v.PlatformBindingID }

// __getPlatformInput is used internally by genqlient
type __getPlatformInput struct {
	PlatformID      string `json:"platformID"`
	PlatformVersion string `json:"platformVersion"`
}

// GetPlatformID returns __getPlatformInput.PlatformID, and is useful for accessing the field via an interface.
func (v *__getPlatformInput) GetPlatformID() string { return v.PlatformID }

// GetPlatformVersion returns __getPlatformInput.PlatformVersion, and is useful for accessing the field via an interface.
func (v *__getPlatformInput) GetPlatformVersion() string { return v.PlatformVersion }

// __updateClusterInput is used internally by genqlient
type __updateClusterInput struct {
	Id         string  `json:"id"`
	Name       *string `json:"name"`
	Server     *string `json:"server"`
	Ca         *string `json:"ca"`
	Token      *string `json:"token"`
	ApiVersion *string `json:"apiVersion"`
	Context    *string `json:"context"`
}

// GetId returns __updateClusterInput.Id, and is useful for accessing the field via an interface.
func (v *__updateClusterInput) GetId() string { return v.Id }

// GetName returns __updateClusterInput.Name, and is useful for accessing the field via an interface.
func (v *__updateClusterInput) GetName() *string { return v.Name }

// GetServer returns __updateClusterInput.Server, and is useful for accessing the field via an interface.
func (v *__updateClusterInput) GetServer() *string { return v.Server }

// GetCa returns __updateClusterInput.Ca, and is useful for accessing the field via an interface.
func (v *__updateClusterInput) GetCa() *string { return v.Ca }

// GetToken returns __updateClusterInput.Token, and is useful for accessing the field via an interface.
func (v *__updateClusterInput) GetToken() *string { return v.Token }

// GetApiVersion returns __updateClusterInput.ApiVersion, and is useful for accessing the field via an interface.
func (v *__updateClusterInput) GetApiVersion() *string { return v.ApiVersion }

// GetContext returns __updateClusterInput.Context, and is useful for accessing the field via an interface.
func (v *__updateClusterInput) GetContext() *string { return v.Context }

// __updatePlatformBindingInput is used internally by genqlient
type __updatePlatformBindingInput struct {
	ClusterID         string  `json:"clusterID"`
	PlatformBindingID string  `json:"platformBindingID"`
	PlatformConfigID  *string `json:"platformConfigID"`
	PlatformVersion   *string `json:"platformVersion"`
}

// GetClusterID returns __updatePlatformBindingInput.ClusterID, and is useful for accessing the field via an interface.
func (v *__updatePlatformBindingInput) GetClusterID() string { return v.ClusterID }

// GetPlatformBindingID returns __updatePlatformBindingInput.PlatformBindingID, and is useful for accessing the field via an interface.
func (v *__updatePlatformBindingInput) GetPlatformBindingID() string { return v.PlatformBindingID }

// GetPlatformConfigID returns __updatePlatformBindingInput.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *__updatePlatformBindingInput) GetPlatformConfigID() *string { return v.PlatformConfigID }

// GetPlatformVersion returns __updatePlatformBindingInput.PlatformVersion, and is useful for accessing the field via an interface.
func (v *__updatePlatformBindingInput) GetPlatformVersion() *string { return v.PlatformVersion }

// __updatePrivateClusterInput is used internally by genqlient
type __updatePrivateClusterInput struct {
	Id                 string  `json:"id"`
	Name               *string `json:"name"`
	Token              *string `json:"token"`
	PrivateTunnelToken *string `json:"privateTunnelToken"`
	ApiVersion         *string `json:"apiVersion"`
	Context            *string `json:"context"`
}

// GetId returns __updatePrivateClusterInput.Id, and is useful for accessing the field via an interface.
func (v *__updatePrivateClusterInput) GetId() string { return v.Id }

// GetName returns __updatePrivateClusterInput.Name, and is useful for accessing the field via an interface.
func (v *__updatePrivateClusterInput) GetName() *string { return v.Name }

// GetToken returns __updatePrivateClusterInput.Token, and is useful for accessing the field via an interface.
func (v *__updatePrivateClusterInput) GetToken() *string { return v.Token }

// GetPrivateTunnelToken returns __updatePrivateClusterInput.PrivateTunnelToken, and is useful for accessing the field via an interface.
func (v *__updatePrivateClusterInput) GetPrivateTunnelToken() *string { return v.PrivateTunnelToken }

// GetApiVersion returns __updatePrivateClusterInput.ApiVersion, and is useful for accessing the field via an interface.
func (v *__updatePrivateClusterInput) GetApiVersion() *string { return v.ApiVersion }

// GetContext returns __updatePrivateClusterInput.Context, and is useful for accessing the field via an interface.
func (v *__updatePrivateClusterInput) GetContext() *string { return v.Context }

// createClusterCreateClusterClusterRedacted includes the requested fields of the GraphQL type ClusterRedacted.
type createClusterCreateClusterClusterRedacted struct {
	ClusterID string `json:"clusterID"`
}

// GetClusterID returns createClusterCreateClusterClusterRedacted.ClusterID, and is useful for accessing the field via an interface.
func (v *createClusterCreateClusterClusterRedacted) GetClusterID() string { return v.ClusterID }

// createClusterResponse is returned by createCluster on success.
type createClusterResponse struct {
	CreateCluster *createClusterCreateClusterClusterRedacted `json:"createCluster"`
}

// GetCreateCluster returns createClusterResponse.CreateCluster, and is useful for accessing the field via an interface.
func (v *createClusterResponse) GetCreateCluster() *createClusterCreateClusterClusterRedacted {
	return v.CreateCluster
}

// createPlatformBindingCreatePlatformBinding includes the requested fields of the GraphQL type PlatformBinding.
type createPlatformBindingCreatePlatformBinding struct {
	PlatformBindingID string                `json:"platformBindingID"`
	Status            PlatformBindingStatus `json:"status"`
}

// GetPlatformBindingID returns createPlatformBindingCreatePlatformBinding.PlatformBindingID, and is useful for accessing the field via an interface.
func (v *createPlatformBindingCreatePlatformBinding) GetPlatformBindingID() string {
	return v.PlatformBindingID
}

// GetStatus returns createPlatformBindingCreatePlatformBinding.Status, and is useful for accessing the field via an interface.
func (v *createPlatformBindingCreatePlatformBinding) GetStatus() PlatformBindingStatus {
	return v.Status
}

// createPlatformBindingResponse is returned by createPlatformBinding on success.
type createPlatformBindingResponse struct {
	CreatePlatformBinding *createPlatformBindingCreatePlatformBinding `json:"createPlatformBinding"`
}

// GetCreatePlatformBinding returns createPlatformBindingResponse.CreatePlatformBinding, and is useful for accessing the field via an interface.
func (v *createPlatformBindingResponse) GetCreatePlatformBinding() *createPlatformBindingCreatePlatformBinding {
	return v.CreatePlatformBinding
}

// createPlatformConfigCreatePlatformConfig includes the requested fields of the GraphQL type PlatformConfig.
type createPlatformConfigCreatePlatformConfig struct {
	PlatformConfigID string `json:"platformConfigID"`
}

// GetPlatformConfigID returns createPlatformConfigCreatePlatformConfig.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *createPlatformConfigCreatePlatformConfig) GetPlatformConfigID() string {
	return v.PlatformConfigID
}

// createPlatformConfigResponse is returned by createPlatformConfig on success.
type createPlatformConfigResponse struct {
	CreatePlatformConfig *createPlatformConfigCreatePlatformConfig `json:"createPlatformConfig"`
}

// GetCreatePlatformConfig returns createPlatformConfigResponse.CreatePlatformConfig, and is useful for accessing the field via an interface.
func (v *createPlatformConfigResponse) GetCreatePlatformConfig() *createPlatformConfigCreatePlatformConfig {
	return v.CreatePlatformConfig
}

// createPrivateClusterCreatePrivateClusterClusterRedacted includes the requested fields of the GraphQL type ClusterRedacted.
type createPrivateClusterCreatePrivateClusterClusterRedacted struct {
	ClusterID string `json:"clusterID"`
}

// GetClusterID returns createPrivateClusterCreatePrivateClusterClusterRedacted.ClusterID, and is useful for accessing the field via an interface.
func (v *createPrivateClusterCreatePrivateClusterClusterRedacted) GetClusterID() string {
	return v.ClusterID
}

// createPrivateClusterResponse is returned by createPrivateCluster on success.
type createPrivateClusterResponse struct {
	CreatePrivateCluster *createPrivateClusterCreatePrivateClusterClusterRedacted `json:"createPrivateCluster"`
}

// GetCreatePrivateCluster returns createPrivateClusterResponse.CreatePrivateCluster, and is useful for accessing the field via an interface.
func (v *createPrivateClusterResponse) GetCreatePrivateCluster() *createPrivateClusterCreatePrivateClusterClusterRedacted {
	return v.CreatePrivateCluster
}

// deleteClusterDeleteClusterClusterRedacted includes the requested fields of the GraphQL type ClusterRedacted.
type deleteClusterDeleteClusterClusterRedacted struct {
	ClusterID string `json:"clusterID"`
}

// GetClusterID returns deleteClusterDeleteClusterClusterRedacted.ClusterID, and is useful for accessing the field via an interface.
func (v *deleteClusterDeleteClusterClusterRedacted) GetClusterID() string { return v.ClusterID }

// deleteClusterResponse is returned by deleteCluster on success.
type deleteClusterResponse struct {
	DeleteCluster *deleteClusterDeleteClusterClusterRedacted `json:"deleteCluster"`
}

// GetDeleteCluster returns deleteClusterResponse.DeleteCluster, and is useful for accessing the field via an interface.
func (v *deleteClusterResponse) GetDeleteCluster() *deleteClusterDeleteClusterClusterRedacted {
	return v.DeleteCluster
}

// deletePlatformBindingDeletePlatformBinding includes the requested fields of the GraphQL type PlatformBinding.
type deletePlatformBindingDeletePlatformBinding struct {
	PlatformID string `json:"platformID"`
}

// GetPlatformID returns deletePlatformBindingDeletePlatformBinding.PlatformID, and is useful for accessing the field via an interface.
func (v *deletePlatformBindingDeletePlatformBinding) GetPlatformID() string { return v.PlatformID }

// deletePlatformBindingResponse is returned by deletePlatformBinding on success.
type deletePlatformBindingResponse struct {
	DeletePlatformBinding *deletePlatformBindingDeletePlatformBinding `json:"deletePlatformBinding"`
}

// GetDeletePlatformBinding returns deletePlatformBindingResponse.DeletePlatformBinding, and is useful for accessing the field via an interface.
func (v *deletePlatformBindingResponse) GetDeletePlatformBinding() *deletePlatformBindingDeletePlatformBinding {
	return v.DeletePlatformBinding
}

// deletePlatformConfigDeletePlatformConfig includes the requested fields of the GraphQL type PlatformConfig.
type deletePlatformConfigDeletePlatformConfig struct {
	PlatformConfigID string `json:"platformConfigID"`
}

// GetPlatformConfigID returns deletePlatformConfigDeletePlatformConfig.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *deletePlatformConfigDeletePlatformConfig) GetPlatformConfigID() string {
	return v.PlatformConfigID
}

// deletePlatformConfigResponse is returned by deletePlatformConfig on success.
type deletePlatformConfigResponse struct {
	DeletePlatformConfig *deletePlatformConfigDeletePlatformConfig `json:"deletePlatformConfig"`
}

// GetDeletePlatformConfig returns deletePlatformConfigResponse.DeletePlatformConfig, and is useful for accessing the field via an interface.
func (v *deletePlatformConfigResponse) GetDeletePlatformConfig() *deletePlatformConfigDeletePlatformConfig {
	return v.DeletePlatformConfig
}

// getClusterGetClusterClusterRedacted includes the requested fields of the GraphQL type ClusterRedacted.
type getClusterGetClusterClusterRedacted struct {
	AccountID          string                                                       `json:"accountID"`
	Ca                 *string                                                      `json:"ca"`
	ClusterID          string                                                       `json:"clusterID"`
	Name               string                                                       `json:"name"`
	Server             *string                                                      `json:"server"`
	PrivateTunnelToken *string                                                      `json:"privateTunnelToken"`
	ApiVersion         string                                                       `json:"apiVersion"`
	Context            *string                                                      `json:"context"`
	Bindings           []getClusterGetClusterClusterRedactedBindingsPlatformBinding `json:"bindings"`
}

// GetAccountID returns getClusterGetClusterClusterRedacted.AccountID, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedacted) GetAccountID() string { return v.AccountID }

// GetCa returns getClusterGetClusterClusterRedacted.Ca, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedacted) GetCa() *string { return v.Ca }

// GetClusterID returns getClusterGetClusterClusterRedacted.ClusterID, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedacted) GetClusterID() string { return v.ClusterID }

// GetName returns getClusterGetClusterClusterRedacted.Name, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedacted) GetName() string { return v.Name }

// GetServer returns getClusterGetClusterClusterRedacted.Server, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedacted) GetServer() *string { return v.Server }

// GetPrivateTunnelToken returns getClusterGetClusterClusterRedacted.PrivateTunnelToken, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedacted) GetPrivateTunnelToken() *string {
	return v.PrivateTunnelToken
}

// GetApiVersion returns getClusterGetClusterClusterRedacted.ApiVersion, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedacted) GetApiVersion() string { return v.ApiVersion }

// GetContext returns getClusterGetClusterClusterRedacted.Context, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedacted) GetContext() *string { return v.Context }

// GetBindings returns getClusterGetClusterClusterRedacted.Bindings, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedacted) GetBindings() []getClusterGetClusterClusterRedactedBindingsPlatformBinding {
	return v.Bindings
}

// getClusterGetClusterClusterRedactedBindingsPlatformBinding includes the requested fields of the GraphQL type PlatformBinding.
type getClusterGetClusterClusterRedactedBindingsPlatformBinding struct {
	PlatformBindingID string                `json:"platformBindingID"`
	PlatformConfigID  string                `json:"platformConfigID"`
	PlatformID        string                `json:"platformID"`
	PlatformVersion   string                `json:"platformVersion"`
	Status            PlatformBindingStatus `json:"status"`
}

// GetPlatformBindingID returns getClusterGetClusterClusterRedactedBindingsPlatformBinding.PlatformBindingID, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedactedBindingsPlatformBinding) GetPlatformBindingID() string {
	return v.PlatformBindingID
}

// GetPlatformConfigID returns getClusterGetClusterClusterRedactedBindingsPlatformBinding.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedactedBindingsPlatformBinding) GetPlatformConfigID() string {
	return v.PlatformConfigID
}

// GetPlatformID returns getClusterGetClusterClusterRedactedBindingsPlatformBinding.PlatformID, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedactedBindingsPlatformBinding) GetPlatformID() string {
	return v.PlatformID
}

// GetPlatformVersion returns getClusterGetClusterClusterRedactedBindingsPlatformBinding.PlatformVersion, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedactedBindingsPlatformBinding) GetPlatformVersion() string {
	return v.PlatformVersion
}

// GetStatus returns getClusterGetClusterClusterRedactedBindingsPlatformBinding.Status, and is useful for accessing the field via an interface.
func (v *getClusterGetClusterClusterRedactedBindingsPlatformBinding) GetStatus() PlatformBindingStatus {
	return v.Status
}

// getClusterResponse is returned by getCluster on success.
type getClusterResponse struct {
	GetCluster *getClusterGetClusterClusterRedacted `json:"getCluster"`
}

// GetGetCluster returns getClusterResponse.GetCluster, and is useful for accessing the field via an interface.
func (v *getClusterResponse) GetGetCluster() *getClusterGetClusterClusterRedacted {
	return v.GetCluster
}

// getPlatformBindingGetPlatformBinding includes the requested fields of the GraphQL type PlatformBinding.
type getPlatformBindingGetPlatformBinding struct {
	PlatformConfigID string                `json:"platformConfigID"`
	PlatformID       string                `json:"platformID"`
	PlatformVersion  string                `json:"platformVersion"`
	Status           PlatformBindingStatus `json:"status"`
}

// GetPlatformConfigID returns getPlatformBindingGetPlatformBinding.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *getPlatformBindingGetPlatformBinding) GetPlatformConfigID() string {
	return v.PlatformConfigID
}

// GetPlatformID returns getPlatformBindingGetPlatformBinding.PlatformID, and is useful for accessing the field via an interface.
func (v *getPlatformBindingGetPlatformBinding) GetPlatformID() string { return v.PlatformID }

// GetPlatformVersion returns getPlatformBindingGetPlatformBinding.PlatformVersion, and is useful for accessing the field via an interface.
func (v *getPlatformBindingGetPlatformBinding) GetPlatformVersion() string { return v.PlatformVersion }

// GetStatus returns getPlatformBindingGetPlatformBinding.Status, and is useful for accessing the field via an interface.
func (v *getPlatformBindingGetPlatformBinding) GetStatus() PlatformBindingStatus { return v.Status }

// getPlatformBindingResponse is returned by getPlatformBinding on success.
type getPlatformBindingResponse struct {
	GetPlatformBinding *getPlatformBindingGetPlatformBinding `json:"getPlatformBinding"`
}

// GetGetPlatformBinding returns getPlatformBindingResponse.GetPlatformBinding, and is useful for accessing the field via an interface.
func (v *getPlatformBindingResponse) GetGetPlatformBinding() *getPlatformBindingGetPlatformBinding {
	return v.GetPlatformBinding
}

// getPlatformGetPlatform includes the requested fields of the GraphQL type Platform.
type getPlatformGetPlatform struct {
	AccountID       *string                                         `json:"accountID"`
	CatalogedDate   *string                                         `json:"catalogedDate"`
	Description     *string                                         `json:"description"`
	Name            string                                          `json:"name"`
	PlatformID      string                                          `json:"platformID"`
	Configs         []getPlatformGetPlatformConfigsPlatformConfig   `json:"configs"`
	PlatformVersion string                                          `json:"platformVersion"`
	Services        []getPlatformGetPlatformServicesPlatformService `json:"services"`
	MinAPIVersion   string                                          `json:"minAPIVersion"`
	MaxAPIVersion   string                                          `json:"maxAPIVersion"`
}

// GetAccountID returns getPlatformGetPlatform.AccountID, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetAccountID() *string { return v.AccountID }

// GetCatalogedDate returns getPlatformGetPlatform.CatalogedDate, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetCatalogedDate() *string { return v.CatalogedDate }

// GetDescription returns getPlatformGetPlatform.Description, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetDescription() *string { return v.Description }

// GetName returns getPlatformGetPlatform.Name, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetName() string { return v.Name }

// GetPlatformID returns getPlatformGetPlatform.PlatformID, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetPlatformID() string { return v.PlatformID }

// GetConfigs returns getPlatformGetPlatform.Configs, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetConfigs() []getPlatformGetPlatformConfigsPlatformConfig {
	return v.Configs
}

// GetPlatformVersion returns getPlatformGetPlatform.PlatformVersion, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetPlatformVersion() string { return v.PlatformVersion }

// GetServices returns getPlatformGetPlatform.Services, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetServices() []getPlatformGetPlatformServicesPlatformService {
	return v.Services
}

// GetMinAPIVersion returns getPlatformGetPlatform.MinAPIVersion, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetMinAPIVersion() string { return v.MinAPIVersion }

// GetMaxAPIVersion returns getPlatformGetPlatform.MaxAPIVersion, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatform) GetMaxAPIVersion() string { return v.MaxAPIVersion }

// getPlatformGetPlatformConfigsPlatformConfig includes the requested fields of the GraphQL type PlatformConfig.
type getPlatformGetPlatformConfigsPlatformConfig struct {
	AccountID        *string `json:"accountID"`
	Config           string  `json:"config"`
	Name             string  `json:"name"`
	PlatformConfigID string  `json:"platformConfigID"`
	PlatformID       string  `json:"platformID"`
	PlatformVersion  string  `json:"platformVersion"`
}

// GetAccountID returns getPlatformGetPlatformConfigsPlatformConfig.AccountID, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformConfigsPlatformConfig) GetAccountID() *string { return v.AccountID }

// GetConfig returns getPlatformGetPlatformConfigsPlatformConfig.Config, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformConfigsPlatformConfig) GetConfig() string { return v.Config }

// GetName returns getPlatformGetPlatformConfigsPlatformConfig.Name, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformConfigsPlatformConfig) GetName() string { return v.Name }

// GetPlatformConfigID returns getPlatformGetPlatformConfigsPlatformConfig.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformConfigsPlatformConfig) GetPlatformConfigID() string {
	return v.PlatformConfigID
}

// GetPlatformID returns getPlatformGetPlatformConfigsPlatformConfig.PlatformID, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformConfigsPlatformConfig) GetPlatformID() string { return v.PlatformID }

// GetPlatformVersion returns getPlatformGetPlatformConfigsPlatformConfig.PlatformVersion, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformConfigsPlatformConfig) GetPlatformVersion() string {
	return v.PlatformVersion
}

// getPlatformGetPlatformServicesPlatformService includes the requested fields of the GraphQL type PlatformService.
type getPlatformGetPlatformServicesPlatformService struct {
	AccountID           *string  `json:"accountID"`
	Delete_dependencies []string `json:"delete_dependencies"`
	Dependencies        []string `json:"dependencies"`
	Name                string   `json:"name"`
	Namespace           string   `json:"namespace"`
	PlatformID          string   `json:"platformID"`
	PlatformServiceID   string   `json:"platformServiceID"`
	PlatformVersion     string   `json:"platformVersion"`
	ServiceID           string   `json:"serviceID"`
	ServiceVersion      string   `json:"serviceVersion"`
}

// GetAccountID returns getPlatformGetPlatformServicesPlatformService.AccountID, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetAccountID() *string { return v.AccountID }

// GetDelete_dependencies returns getPlatformGetPlatformServicesPlatformService.Delete_dependencies, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetDelete_dependencies() []string {
	return v.Delete_dependencies
}

// GetDependencies returns getPlatformGetPlatformServicesPlatformService.Dependencies, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetDependencies() []string {
	return v.Dependencies
}

// GetName returns getPlatformGetPlatformServicesPlatformService.Name, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetName() string { return v.Name }

// GetNamespace returns getPlatformGetPlatformServicesPlatformService.Namespace, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetNamespace() string { return v.Namespace }

// GetPlatformID returns getPlatformGetPlatformServicesPlatformService.PlatformID, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetPlatformID() string { return v.PlatformID }

// GetPlatformServiceID returns getPlatformGetPlatformServicesPlatformService.PlatformServiceID, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetPlatformServiceID() string {
	return v.PlatformServiceID
}

// GetPlatformVersion returns getPlatformGetPlatformServicesPlatformService.PlatformVersion, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetPlatformVersion() string {
	return v.PlatformVersion
}

// GetServiceID returns getPlatformGetPlatformServicesPlatformService.ServiceID, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetServiceID() string { return v.ServiceID }

// GetServiceVersion returns getPlatformGetPlatformServicesPlatformService.ServiceVersion, and is useful for accessing the field via an interface.
func (v *getPlatformGetPlatformServicesPlatformService) GetServiceVersion() string {
	return v.ServiceVersion
}

// getPlatformResponse is returned by getPlatform on success.
type getPlatformResponse struct {
	GetPlatform *getPlatformGetPlatform `json:"getPlatform"`
}

// GetGetPlatform returns getPlatformResponse.GetPlatform, and is useful for accessing the field via an interface.
func (v *getPlatformResponse) GetGetPlatform() *getPlatformGetPlatform { return v.GetPlatform }

// listClusterListClusterClusterConnection includes the requested fields of the GraphQL type ClusterConnection.
type listClusterListClusterClusterConnection struct {
	Items []*listClusterListClusterClusterConnectionItemsClusterRedacted `json:"items"`
}

// GetItems returns listClusterListClusterClusterConnection.Items, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnection) GetItems() []*listClusterListClusterClusterConnectionItemsClusterRedacted {
	return v.Items
}

// listClusterListClusterClusterConnectionItemsClusterRedacted includes the requested fields of the GraphQL type ClusterRedacted.
type listClusterListClusterClusterConnectionItemsClusterRedacted struct {
	AccountID          string                                                                               `json:"accountID"`
	Ca                 *string                                                                              `json:"ca"`
	ClusterID          string                                                                               `json:"clusterID"`
	Name               string                                                                               `json:"name"`
	Server             *string                                                                              `json:"server"`
	PrivateTunnelToken *string                                                                              `json:"privateTunnelToken"`
	ApiVersion         string                                                                               `json:"apiVersion"`
	Context            *string                                                                              `json:"context"`
	Bindings           []listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding `json:"bindings"`
}

// GetAccountID returns listClusterListClusterClusterConnectionItemsClusterRedacted.AccountID, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedacted) GetAccountID() string {
	return v.AccountID
}

// GetCa returns listClusterListClusterClusterConnectionItemsClusterRedacted.Ca, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedacted) GetCa() *string { return v.Ca }

// GetClusterID returns listClusterListClusterClusterConnectionItemsClusterRedacted.ClusterID, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedacted) GetClusterID() string {
	return v.ClusterID
}

// GetName returns listClusterListClusterClusterConnectionItemsClusterRedacted.Name, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedacted) GetName() string { return v.Name }

// GetServer returns listClusterListClusterClusterConnectionItemsClusterRedacted.Server, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedacted) GetServer() *string {
	return v.Server
}

// GetPrivateTunnelToken returns listClusterListClusterClusterConnectionItemsClusterRedacted.PrivateTunnelToken, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedacted) GetPrivateTunnelToken() *string {
	return v.PrivateTunnelToken
}

// GetApiVersion returns listClusterListClusterClusterConnectionItemsClusterRedacted.ApiVersion, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedacted) GetApiVersion() string {
	return v.ApiVersion
}

// GetContext returns listClusterListClusterClusterConnectionItemsClusterRedacted.Context, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedacted) GetContext() *string {
	return v.Context
}

// GetBindings returns listClusterListClusterClusterConnectionItemsClusterRedacted.Bindings, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedacted) GetBindings() []listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding {
	return v.Bindings
}

// listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding includes the requested fields of the GraphQL type PlatformBinding.
type listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding struct {
	PlatformBindingID string `json:"platformBindingID"`
	PlatformConfigID  string `json:"platformConfigID"`
	PlatformID        string `json:"platformID"`
	PlatformVersion   string `json:"platformVersion"`
}

// GetPlatformBindingID returns listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding.PlatformBindingID, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding) GetPlatformBindingID() string {
	return v.PlatformBindingID
}

// GetPlatformConfigID returns listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding) GetPlatformConfigID() string {
	return v.PlatformConfigID
}

// GetPlatformID returns listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding.PlatformID, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding) GetPlatformID() string {
	return v.PlatformID
}

// GetPlatformVersion returns listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding.PlatformVersion, and is useful for accessing the field via an interface.
func (v *listClusterListClusterClusterConnectionItemsClusterRedactedBindingsPlatformBinding) GetPlatformVersion() string {
	return v.PlatformVersion
}

// listClusterResponse is returned by listCluster on success.
type listClusterResponse struct {
	ListCluster *listClusterListClusterClusterConnection `json:"listCluster"`
}

// GetListCluster returns listClusterResponse.ListCluster, and is useful for accessing the field via an interface.
func (v *listClusterResponse) GetListCluster() *listClusterListClusterClusterConnection {
	return v.ListCluster
}

// listPlatformListPlatformPlatformConnection includes the requested fields of the GraphQL type PlatformConnection.
type listPlatformListPlatformPlatformConnection struct {
	Items []*listPlatformListPlatformPlatformConnectionItemsPlatform `json:"items"`
}

// GetItems returns listPlatformListPlatformPlatformConnection.Items, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnection) GetItems() []*listPlatformListPlatformPlatformConnectionItemsPlatform {
	return v.Items
}

// listPlatformListPlatformPlatformConnectionItemsPlatform includes the requested fields of the GraphQL type Platform.
type listPlatformListPlatformPlatformConnectionItemsPlatform struct {
	AccountID       *string                                                                          `json:"accountID"`
	CatalogedDate   *string                                                                          `json:"catalogedDate"`
	Description     *string                                                                          `json:"description"`
	Name            string                                                                           `json:"name"`
	PlatformID      string                                                                           `json:"platformID"`
	PlatformVersion string                                                                           `json:"platformVersion"`
	Configs         []listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig   `json:"configs"`
	Services        []listPlatformListPlatformPlatformConnectionItemsPlatformServicesPlatformService `json:"services"`
	MinAPIVersion   string                                                                           `json:"minAPIVersion"`
	MaxAPIVersion   string                                                                           `json:"maxAPIVersion"`
}

// GetAccountID returns listPlatformListPlatformPlatformConnectionItemsPlatform.AccountID, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetAccountID() *string {
	return v.AccountID
}

// GetCatalogedDate returns listPlatformListPlatformPlatformConnectionItemsPlatform.CatalogedDate, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetCatalogedDate() *string {
	return v.CatalogedDate
}

// GetDescription returns listPlatformListPlatformPlatformConnectionItemsPlatform.Description, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetDescription() *string {
	return v.Description
}

// GetName returns listPlatformListPlatformPlatformConnectionItemsPlatform.Name, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetName() string { return v.Name }

// GetPlatformID returns listPlatformListPlatformPlatformConnectionItemsPlatform.PlatformID, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetPlatformID() string {
	return v.PlatformID
}

// GetPlatformVersion returns listPlatformListPlatformPlatformConnectionItemsPlatform.PlatformVersion, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetPlatformVersion() string {
	return v.PlatformVersion
}

// GetConfigs returns listPlatformListPlatformPlatformConnectionItemsPlatform.Configs, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetConfigs() []listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig {
	return v.Configs
}

// GetServices returns listPlatformListPlatformPlatformConnectionItemsPlatform.Services, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetServices() []listPlatformListPlatformPlatformConnectionItemsPlatformServicesPlatformService {
	return v.Services
}

// GetMinAPIVersion returns listPlatformListPlatformPlatformConnectionItemsPlatform.MinAPIVersion, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetMinAPIVersion() string {
	return v.MinAPIVersion
}

// GetMaxAPIVersion returns listPlatformListPlatformPlatformConnectionItemsPlatform.MaxAPIVersion, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatform) GetMaxAPIVersion() string {
	return v.MaxAPIVersion
}

// listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig includes the requested fields of the GraphQL type PlatformConfig.
type listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig struct {
	AccountID        *string `json:"accountID"`
	Config           string  `json:"config"`
	Name             string  `json:"name"`
	PlatformConfigID string  `json:"platformConfigID"`
	PlatformID       string  `json:"platformID"`
	PlatformVersion  string  `json:"platformVersion"`
}

// GetAccountID returns listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig.AccountID, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig) GetAccountID() *string {
	return v.AccountID
}

// GetConfig returns listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig.Config, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig) GetConfig() string {
	return v.Config
}

// GetName returns listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig.Name, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig) GetName() string {
	return v.Name
}

// GetPlatformConfigID returns listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig) GetPlatformConfigID() string {
	return v.PlatformConfigID
}

// GetPlatformID returns listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig.PlatformID, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig) GetPlatformID() string {
	return v.PlatformID
}

// GetPlatformVersion returns listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig.PlatformVersion, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatformConfigsPlatformConfig) GetPlatformVersion() string {
	return v.PlatformVersion
}

// listPlatformListPlatformPlatformConnectionItemsPlatformServicesPlatformService includes the requested fields of the GraphQL type PlatformService.
type listPlatformListPlatformPlatformConnectionItemsPlatformServicesPlatformService struct {
	Name      string `json:"name"`
	ServiceID string `json:"serviceID"`
}

// GetName returns listPlatformListPlatformPlatformConnectionItemsPlatformServicesPlatformService.Name, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatformServicesPlatformService) GetName() string {
	return v.Name
}

// GetServiceID returns listPlatformListPlatformPlatformConnectionItemsPlatformServicesPlatformService.ServiceID, and is useful for accessing the field via an interface.
func (v *listPlatformListPlatformPlatformConnectionItemsPlatformServicesPlatformService) GetServiceID() string {
	return v.ServiceID
}

// listPlatformResponse is returned by listPlatform on success.
type listPlatformResponse struct {
	ListPlatform *listPlatformListPlatformPlatformConnection `json:"listPlatform"`
}

// GetListPlatform returns listPlatformResponse.ListPlatform, and is useful for accessing the field via an interface.
func (v *listPlatformResponse) GetListPlatform() *listPlatformListPlatformPlatformConnection {
	return v.ListPlatform
}

// updateClusterResponse is returned by updateCluster on success.
type updateClusterResponse struct {
	UpdateCluster *updateClusterUpdateClusterClusterRedacted `json:"updateCluster"`
}

// GetUpdateCluster returns updateClusterResponse.UpdateCluster, and is useful for accessing the field via an interface.
func (v *updateClusterResponse) GetUpdateCluster() *updateClusterUpdateClusterClusterRedacted {
	return v.UpdateCluster
}

// updateClusterUpdateClusterClusterRedacted includes the requested fields of the GraphQL type ClusterRedacted.
type updateClusterUpdateClusterClusterRedacted struct {
	ClusterID string `json:"clusterID"`
}

// GetClusterID returns updateClusterUpdateClusterClusterRedacted.ClusterID, and is useful for accessing the field via an interface.
func (v *updateClusterUpdateClusterClusterRedacted) GetClusterID() string { return v.ClusterID }

// updatePlatformBindingResponse is returned by updatePlatformBinding on success.
type updatePlatformBindingResponse struct {
	UpdatePlatformBinding *updatePlatformBindingUpdatePlatformBinding `json:"updatePlatformBinding"`
}

// GetUpdatePlatformBinding returns updatePlatformBindingResponse.UpdatePlatformBinding, and is useful for accessing the field via an interface.
func (v *updatePlatformBindingResponse) GetUpdatePlatformBinding() *updatePlatformBindingUpdatePlatformBinding {
	return v.UpdatePlatformBinding
}

// updatePlatformBindingUpdatePlatformBinding includes the requested fields of the GraphQL type PlatformBinding.
type updatePlatformBindingUpdatePlatformBinding struct {
	Status           PlatformBindingStatus `json:"status"`
	PlatformConfigID string                `json:"platformConfigID"`
	PlatformVersion  string                `json:"platformVersion"`
}

// GetStatus returns updatePlatformBindingUpdatePlatformBinding.Status, and is useful for accessing the field via an interface.
func (v *updatePlatformBindingUpdatePlatformBinding) GetStatus() PlatformBindingStatus {
	return v.Status
}

// GetPlatformConfigID returns updatePlatformBindingUpdatePlatformBinding.PlatformConfigID, and is useful for accessing the field via an interface.
func (v *updatePlatformBindingUpdatePlatformBinding) GetPlatformConfigID() string {
	return v.PlatformConfigID
}

// GetPlatformVersion returns updatePlatformBindingUpdatePlatformBinding.PlatformVersion, and is useful for accessing the field via an interface.
func (v *updatePlatformBindingUpdatePlatformBinding) GetPlatformVersion() string {
	return v.PlatformVersion
}

// updatePrivateClusterResponse is returned by updatePrivateCluster on success.
type updatePrivateClusterResponse struct {
	UpdatePrivateCluster *updatePrivateClusterUpdatePrivateClusterClusterRedacted `json:"updatePrivateCluster"`
}

// GetUpdatePrivateCluster returns updatePrivateClusterResponse.UpdatePrivateCluster, and is useful for accessing the field via an interface.
func (v *updatePrivateClusterResponse) GetUpdatePrivateCluster() *updatePrivateClusterUpdatePrivateClusterClusterRedacted {
	return v.UpdatePrivateCluster
}

// updatePrivateClusterUpdatePrivateClusterClusterRedacted includes the requested fields of the GraphQL type ClusterRedacted.
type updatePrivateClusterUpdatePrivateClusterClusterRedacted struct {
	ClusterID string `json:"clusterID"`
}

// GetClusterID returns updatePrivateClusterUpdatePrivateClusterClusterRedacted.ClusterID, and is useful for accessing the field via an interface.
func (v *updatePrivateClusterUpdatePrivateClusterClusterRedacted) GetClusterID() string {
	return v.ClusterID
}

func createCluster(
	ctx context.Context,
	client graphql.Client,
	name string,
	server string,
	ca string,
	token string,
	apiVersion string,
	context string,
) (*createClusterResponse, error) {
	req := &graphql.Request{
		OpName: "createCluster",
		Query: `
mutation createCluster ($name: String!, $server: String!, $ca: String!, $token: String!, $apiVersion: String!, $context: AWSJSON!) {
	createCluster(input: {name:$name,server:$server,ca:$ca,token:$token,apiVersion:$apiVersion,context:$context}) {
		clusterID
	}
}
`,
		Variables: &__createClusterInput{
			Name:       name,
			Server:     server,
			Ca:         ca,
			Token:      token,
			ApiVersion: apiVersion,
			Context:    context,
		},
	}
	var err error

	var data createClusterResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func createPlatformBinding(
	ctx context.Context,
	client graphql.Client,
	platformVersion string,
	platformID string,
	platformConfigID string,
	clusterID string,
) (*createPlatformBindingResponse, error) {
	req := &graphql.Request{
		OpName: "createPlatformBinding",
		Query: `
mutation createPlatformBinding ($platformVersion: String!, $platformID: ID!, $platformConfigID: ID!, $clusterID: ID!) {
	createPlatformBinding(input: {platformVersion:$platformVersion,platformID:$platformID,platformConfigID:$platformConfigID,clusterID:$clusterID}) {
		platformBindingID
		status
	}
}
`,
		Variables: &__createPlatformBindingInput{
			PlatformVersion:  platformVersion,
			PlatformID:       platformID,
			PlatformConfigID: platformConfigID,
			ClusterID:        clusterID,
		},
	}
	var err error

	var data createPlatformBindingResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func createPlatformConfig(
	ctx context.Context,
	client graphql.Client,
	config string,
	name string,
	platformID string,
	platformVersion string,
) (*createPlatformConfigResponse, error) {
	req := &graphql.Request{
		OpName: "createPlatformConfig",
		Query: `
mutation createPlatformConfig ($config: AWSJSON!, $name: String!, $platformID: ID!, $platformVersion: String!) {
	createPlatformConfig(input: {config:$config,name:$name,platformID:$platformID,platformVersion:$platformVersion}) {
		platformConfigID
	}
}
`,
		Variables: &__createPlatformConfigInput{
			Config:          config,
			Name:            name,
			PlatformID:      platformID,
			PlatformVersion: platformVersion,
		},
	}
	var err error

	var data createPlatformConfigResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func createPrivateCluster(
	ctx context.Context,
	client graphql.Client,
	name string,
	token string,
	privateTunnelToken string,
	apiVersion string,
	context string,
) (*createPrivateClusterResponse, error) {
	req := &graphql.Request{
		OpName: "createPrivateCluster",
		Query: `
mutation createPrivateCluster ($name: String!, $token: String!, $privateTunnelToken: String!, $apiVersion: String!, $context: AWSJSON!) {
	createPrivateCluster(input: {name:$name,token:$token,privateTunnelToken:$privateTunnelToken,apiVersion:$apiVersion,context:$context}) {
		clusterID
	}
}
`,
		Variables: &__createPrivateClusterInput{
			Name:               name,
			Token:              token,
			PrivateTunnelToken: privateTunnelToken,
			ApiVersion:         apiVersion,
			Context:            context,
		},
	}
	var err error

	var data createPrivateClusterResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func deleteCluster(
	ctx context.Context,
	client graphql.Client,
	id string,
) (*deleteClusterResponse, error) {
	req := &graphql.Request{
		OpName: "deleteCluster",
		Query: `
mutation deleteCluster ($id: ID!) {
	deleteCluster(input: {clusterID:$id}) {
		clusterID
	}
}
`,
		Variables: &__deleteClusterInput{
			Id: id,
		},
	}
	var err error

	var data deleteClusterResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func deletePlatformBinding(
	ctx context.Context,
	client graphql.Client,
	clusterID string,
	platformBindingID string,
) (*deletePlatformBindingResponse, error) {
	req := &graphql.Request{
		OpName: "deletePlatformBinding",
		Query: `
mutation deletePlatformBinding ($clusterID: ID!, $platformBindingID: ID!) {
	deletePlatformBinding(input: {clusterID:$clusterID,platformBindingID:$platformBindingID}) {
		platformID
	}
}
`,
		Variables: &__deletePlatformBindingInput{
			ClusterID:         clusterID,
			PlatformBindingID: platformBindingID,
		},
	}
	var err error

	var data deletePlatformBindingResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func deletePlatformConfig(
	ctx context.Context,
	client graphql.Client,
	platformID string,
	platformConfigID string,
) (*deletePlatformConfigResponse, error) {
	req := &graphql.Request{
		OpName: "deletePlatformConfig",
		Query: `
mutation deletePlatformConfig ($platformID: ID!, $platformConfigID: ID!) {
	deletePlatformConfig(input: {platformConfigID:$platformConfigID,platformID:$platformID}) {
		platformConfigID
	}
}
`,
		Variables: &__deletePlatformConfigInput{
			PlatformID:       platformID,
			PlatformConfigID: platformConfigID,
		},
	}
	var err error

	var data deletePlatformConfigResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func getCluster(
	ctx context.Context,
	client graphql.Client,
	id string,
) (*getClusterResponse, error) {
	req := &graphql.Request{
		OpName: "getCluster",
		Query: `
query getCluster ($id: ID!) {
	getCluster(clusterID: $id) {
		accountID
		ca
		clusterID
		name
		server
		privateTunnelToken
		apiVersion
		context
		bindings {
			platformBindingID
			platformConfigID
			platformID
			platformVersion
			status
		}
	}
}
`,
		Variables: &__getClusterInput{
			Id: id,
		},
	}
	var err error

	var data getClusterResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func getPlatform(
	ctx context.Context,
	client graphql.Client,
	platformID string,
	platformVersion string,
) (*getPlatformResponse, error) {
	req := &graphql.Request{
		OpName: "getPlatform",
		Query: `
query getPlatform ($platformID: ID!, $platformVersion: String!) {
	getPlatform(platformID: $platformID, platformVersion: $platformVersion) {
		accountID
		catalogedDate
		description
		name
		platformID
		configs {
			accountID
			config
			name
			platformConfigID
			platformID
			platformVersion
		}
		platformVersion
		services {
			accountID
			delete_dependencies
			dependencies
			name
			namespace
			platformID
			platformServiceID
			platformVersion
			serviceID
			serviceVersion
		}
		minAPIVersion
		maxAPIVersion
	}
}
`,
		Variables: &__getPlatformInput{
			PlatformID:      platformID,
			PlatformVersion: platformVersion,
		},
	}
	var err error

	var data getPlatformResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func getPlatformBinding(
	ctx context.Context,
	client graphql.Client,
	clusterID string,
	platformBindingID string,
) (*getPlatformBindingResponse, error) {
	req := &graphql.Request{
		OpName: "getPlatformBinding",
		Query: `
query getPlatformBinding ($clusterID: ID!, $platformBindingID: ID!) {
	getPlatformBinding(clusterID: $clusterID, platformBindingID: $platformBindingID) {
		platformConfigID
		platformID
		platformVersion
		status
	}
}
`,
		Variables: &__getPlatformBindingInput{
			ClusterID:         clusterID,
			PlatformBindingID: platformBindingID,
		},
	}
	var err error

	var data getPlatformBindingResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func listCluster(
	ctx context.Context,
	client graphql.Client,
) (*listClusterResponse, error) {
	req := &graphql.Request{
		OpName: "listCluster",
		Query: `
query listCluster {
	listCluster {
		items {
			accountID
			ca
			clusterID
			name
			server
			privateTunnelToken
			apiVersion
			context
			bindings {
				platformBindingID
				platformConfigID
				platformID
				platformVersion
			}
		}
	}
}
`,
	}
	var err error

	var data listClusterResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func listPlatform(
	ctx context.Context,
	client graphql.Client,
) (*listPlatformResponse, error) {
	req := &graphql.Request{
		OpName: "listPlatform",
		Query: `
query listPlatform {
	listPlatform {
		items {
			accountID
			catalogedDate
			description
			name
			platformID
			platformVersion
			configs {
				accountID
				config
				name
				platformConfigID
				platformID
				platformVersion
			}
			services {
				name
				serviceID
			}
			minAPIVersion
			maxAPIVersion
		}
	}
}
`,
	}
	var err error

	var data listPlatformResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func updateCluster(
	ctx context.Context,
	client graphql.Client,
	id string,
	name *string,
	server *string,
	ca *string,
	token *string,
	apiVersion *string,
	context *string,
) (*updateClusterResponse, error) {
	req := &graphql.Request{
		OpName: "updateCluster",
		Query: `
mutation updateCluster ($id: ID!, $name: String, $server: String, $ca: String, $token: String, $apiVersion: String, $context: AWSJSON) {
	updateCluster(input: {clusterID:$id,name:$name,server:$server,ca:$ca,token:$token,apiVersion:$apiVersion,context:$context}) {
		clusterID
	}
}
`,
		Variables: &__updateClusterInput{
			Id:         id,
			Name:       name,
			Server:     server,
			Ca:         ca,
			Token:      token,
			ApiVersion: apiVersion,
			Context:    context,
		},
	}
	var err error

	var data updateClusterResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func updatePlatformBinding(
	ctx context.Context,
	client graphql.Client,
	clusterID string,
	platformBindingID string,
	platformConfigID *string,
	platformVersion *string,
) (*updatePlatformBindingResponse, error) {
	req := &graphql.Request{
		OpName: "updatePlatformBinding",
		Query: `
mutation updatePlatformBinding ($clusterID: ID!, $platformBindingID: ID!, $platformConfigID: ID, $platformVersion: String) {
	updatePlatformBinding(input: {clusterID:$clusterID,platformBindingID:$platformBindingID,platformConfigID:$platformConfigID,platformVersion:$platformVersion}) {
		status
		platformConfigID
		platformVersion
	}
}
`,
		Variables: &__updatePlatformBindingInput{
			ClusterID:         clusterID,
			PlatformBindingID: platformBindingID,
			PlatformConfigID:  platformConfigID,
			PlatformVersion:   platformVersion,
		},
	}
	var err error

	var data updatePlatformBindingResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func updatePrivateCluster(
	ctx context.Context,
	client graphql.Client,
	id string,
	name *string,
	token *string,
	privateTunnelToken *string,
	apiVersion *string,
	context *string,
) (*updatePrivateClusterResponse, error) {
	req := &graphql.Request{
		OpName: "updatePrivateCluster",
		Query: `
mutation updatePrivateCluster ($id: ID!, $name: String, $token: String, $privateTunnelToken: String, $apiVersion: String, $context: AWSJSON) {
	updatePrivateCluster(input: {clusterID:$id,name:$name,token:$token,privateTunnelToken:$privateTunnelToken,apiVersion:$apiVersion,context:$context}) {
		clusterID
	}
}
`,
		Variables: &__updatePrivateClusterInput{
			Id:                 id,
			Name:               name,
			Token:              token,
			PrivateTunnelToken: privateTunnelToken,
			ApiVersion:         apiVersion,
			Context:            context,
		},
	}
	var err error

	var data updatePrivateClusterResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
