package guku

type Cluster = getClusterGetClusterClusterRedacted
type PlatformBinding = getClusterGetClusterClusterRedactedBindingsPlatformBinding
type Platform = getPlatformGetPlatform
type PlatformConfig = getPlatformGetPlatformConfigsPlatformConfig
type PlatformService = getPlatformGetPlatformServicesPlatformService

type ClusterCreate = createClusterCreateClusterClusterRedacted
type ClusterUpdate = updateClusterUpdateClusterClusterRedacted
type ClusterDelete = deleteClusterDeleteClusterClusterRedacted

type PlatformBindingGet = getPlatformBindingGetPlatformBinding
type PlatformBindingCreate = createPlatformBindingCreatePlatformBinding
type PlatformBindingUpdate = updatePlatformBindingUpdatePlatformBinding
type PlatformBindingDelete = deletePlatformBindingDeletePlatformBinding
